---
title: Toan Thang's Home
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
header-img: img/home-bg.jpg
email: 
copyright_name: Than Toan Thang
description: Sharing is learning
baseurl: ''
url: https://thantoanthang.github.io
twitter_username: 
github_username: 
facebook_username: 
email_username:

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
google_tracking_id: UA-81935911-3

# Disqus Comments
disqus:
    # Leave shortname blank to disable comments site-wide.
    # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
    shortname: thantoanthang-com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude:
- less
- node_modules
- Gruntfile.js
- package.json
- README.md
gems:
- jekyll-paginate
- jekyll-feed
